Repository IgniteUI/igniteui-angular, pull requests merged in 2018-03, with the labels that each got.

#681 Added dependencies to hammerjs and @types/hammerjs
  gulpfile.js
Labels: build, npm, status: verified

#696 Changelog update
  CHANGELOG.md
Labels: documentation, status: verified

#692 Reducing normalize styles
  src/core/styles/base/_normalize.scss
Labels: refactoring, status: in-test, styling, version: 5.2.1

#699 fix(themes): Internet Explorer 11 and Edge related fixes
  demos/app/carousel/sample.component.css
  demos/app/carousel/sample.component.html
  demos/app/grid-performance/sample.component.html
  demos/app/grid/sample.component.css
  demos/app/grid/sample.component.html
  demos/app/icon/sample.component.css
  src/core/styles/components/badge/_badge-theme.scss
  src/core/styles/components/button-group/_button-group-theme.scss
  src/core/styles/components/button/_button-theme.scss
  src/core/styles/components/carousel/_carousel-theme.scss
  src/core/styles/components/grid/_grid-theme.scss
  src/core/styles/components/icon/_icon-theme.scss
Labels: ie-11, status: in-test, version: 5.2.1

#700 Merging 5.2.x into master
  demos/app/carousel/sample.component.css
  demos/app/carousel/sample.component.html
  demos/app/grid-performance/sample.component.html
  demos/app/grid/sample.component.css
  demos/app/grid/sample.component.html
  demos/app/icon/sample.component.css
  src/core/styles/components/badge/_badge-theme.scss
  src/core/styles/components/button-group/_button-group-theme.scss
  src/core/styles/components/button/_button-theme.scss
  src/core/styles/components/carousel/_carousel-theme.scss
  src/core/styles/components/grid/_grid-theme.scss
  src/core/styles/components/icon/_icon-theme.scss
Labels: ie-11, status: verified

#687 Various fixes related to column pinning.
  demos/app/grid-column-pinning/sample.component.html
  demos/app/grid-column-pinning/sample.component.ts
  src/core/styles/components/grid/_grid-component.scss
  src/core/styles/components/grid/_grid-theme.scss
  src/core/utils.ts
  src/grid/api.service.ts
  src/grid/cell.component.ts
  src/grid/column.component.ts
  src/grid/grid-header.component.ts
  src/grid/grid.component.html
  src/grid/grid.component.ts
  src/grid/row.component.html
  src/grid/row.component.ts
Labels: grid, pinning

#703 fix(icon): icon alignment issues in IE11
  demos/app/pageHeading/pageHeading.styles.css
  demos/app/pageHeading/pageHeading.template.html
  src/core/styles/base/_index.scss
  src/core/styles/base/_normalize.scss
  src/core/styles/components/badge/_badge-theme.scss
  src/core/styles/components/button/_button-theme.scss
  src/core/styles/components/grid-filtering/_grid-filtering-theme.scss
  src/core/styles/components/icon/_icon-theme.scss
  src/icon/icon.component.html
  src/icon/icon.component.spec.ts
  src/icon/icon.component.ts
Labels: icon, status: verified, styling, version: 5.2.x

#711 Merging 5.2.x into master
  demos/app/pageHeading/pageHeading.styles.css
  demos/app/pageHeading/pageHeading.template.html
  src/core/styles/base/_index.scss
  src/core/styles/base/_normalize.scss
  src/core/styles/components/badge/_badge-theme.scss
  src/core/styles/components/button/_button-theme.scss
  src/core/styles/components/grid-filtering/_grid-filtering-theme.scss
  src/core/styles/components/icon/_icon-theme.scss
  src/icon/icon.component.html
  src/icon/icon.component.spec.ts
  src/icon/icon.component.ts
Labels: version: 5.3.x

#709 change calendar default locale to "en"
  src/calendar/README.md
  src/calendar/calendar.component.ts
Labels: calendar, enhancement, version: 5.2.x

#719 Equal date filter to compare date parts
  src/data-operations/filtering-condition.ts
Labels: status: verified, version: 5.2.x

#720 equals date filter to compare date parts
  src/data-operations/filtering-condition.ts
Labels: status: verified, version: 5.3.x

#722 Add pinning rejection if width of pinned area becomes bigger than the grid width.
  demos/app/grid-column-pinning/sample.component.html
  src/grid/grid.component.ts
Labels: grid, pinning

#727 fix: Ripple right-to-left positioning
  src/core/styles/components/ripple/_ripple-component.scss
  src/core/styles/components/ripple/_ripple-theme.scss
  src/directives/ripple/ripple.directive.ts
Labels: bug, ripple, version: 5.3.x

#729 Design time picker
  demos/style/igniteui-theme.scss
  src/core/styles/components/tiem-picker/_time-picker-component.scss
  src/core/styles/components/tiem-picker/_time-picker-theme.scss
  src/time-picker/time-picker.component.html
  src/time-picker/time-picker.component.scss
  src/time-picker/time-picker.component.ts
  src/time-picker/time-picker.directives.ts
Labels: styling

#732 Fixing an uglify warning in the calendar
  src/calendar/calendar.ts
Labels: refactoring, version: 5.3.x

#733 Fix cells array in row component is not updated when cells are removed from the view.
  src/grid/row.component.ts
Labels: bug, grid, virtualization

#724 IgxGrid and dynamic components with OnPush detection.
  CHANGELOG.md
  src/directives/for-of/for_of.directive.ts
  src/grid/api.service.ts
  src/grid/cell.component.ts
  src/grid/cell.spec.ts
  src/grid/column.component.ts
  src/grid/column.spec.ts
  src/grid/grid-filtering.component.ts
  src/grid/grid-header.component.ts
  src/grid/grid.common.ts
  src/grid/grid.component.html
  src/grid/grid.component.ts
  src/grid/grid.crud.spec.ts
  src/grid/grid.pagination.spec.ts
  src/grid/row.component.html
  src/grid/row.component.ts
Labels: bug, grid, refactoring, version: 5.3.x

#723 feat(icon): implement icon service and multiple font support
  CHANGELOG.md
  demos/app/avatar/sample.module.ts
  demos/app/icon/icon.sample.html
  demos/app/icon/sample.component.ts
  demos/app/icon/sample.module.ts
  demos/index.ejs
  demos/package-lock.json
  demos/package.json
  src/avatar/avatar.component.spec.ts
  src/avatar/avatar.component.ts
  src/badge/badge.component.spec.ts
  src/badge/badge.component.ts
  src/buttonGroup/buttonGroup.component.ts
  src/calendar/calendar.module.ts
  src/carousel/carousel.component.ts
  src/grid/index.ts
  src/icon/icon.component.html
  src/icon/icon.component.spec.ts
  src/icon/icon.component.ts
  src/icon/icon.service.spec.ts
  src/icon/icon.service.ts
  src/icon/index.ts
  src/main.ts
  src/navbar/navbar.component.ts
  src/tabbar/tabbar.component.ts
Labels: feature, icon, version: 5.3.x

#725 docs(themes): reflect change made to the igx-theme mixin
  src/calendar/README.md
  src/calendar/calendar.component.ts
  src/core/styles/README.md
Labels: documentation, theme, version: 5.3.x

#736 Igxgrid filtering dates
  src/data-operations/filtering-condition.ts
  src/grid/grid-filtering.component.ts
Labels: status: awaiting-test

#751 UI tests that involve date picking need to be rewritten
  src/calendar/calendar.component.ts
  src/grid/grid-filtering.spec.ts
Labels: grid, status: verified, tests

#697 igxMask directive initial implementation
  src/directives/mask/README.md
  src/directives/mask/mask-helper.ts
  src/directives/mask/mask.directive.spec.ts
  src/directives/mask/mask.directive.ts
  src/main.ts
Labels: feature, input, mask-editor, status: verified, version: 5.3.x

#756 refactored filtering ui tests
  src/directives/mask/mask.directive.spec.ts
  src/grid/grid-filtering.spec.ts
Labels: status: verified

#766 feat(layout directive): Add flex-basis and default align-items to stretch
  src/directives/layout/layout.directive.spec.ts
  src/directives/layout/layout.directive.ts
Labels: feature, layout, status: awaiting-test, tests

#763 Fixing issue #744 - Last element rendered with igxFor is not always fully visible.
  demos/app/virtual-for-directive/sample.component.html
  src/directives/for-of/for_of.directive.ts
  src/grid/row.component.ts
Labels: status: verified, version: 5.2.x, virtualization

#757 Fixing issue #744 - Last element rendered with igxFor is not always fully visible
  demos/app/virtual-for-directive/sample.component.html
  src/directives/for-of/for_of.directive.ts
  src/grid/row.component.ts
Labels: status: verified, version: 5.3.x, virtualization

#770 Dialog, Calendar and Date Picker Improvements
  demos/app/date-picker/sample.component.html
  demos/app/dialog/sample.component.html
  src/core/styles/components/calendar/_calendar-theme.scss
  src/core/styles/components/date-picker/_date-picker-component.scss
  src/core/styles/components/date-picker/_date-picker-theme.scss
  src/core/styles/components/dialog/_dialog-component.scss
  src/core/styles/components/dialog/_dialog-theme.scss
  src/date-picker/date-picker.component.html
  src/dialog/dialog-content.component.html
  src/dialog/dialog.component.spec.ts
Labels: calendar, date-picker, modal-dialog, status: awaiting-test

#771 Dialog, Calendar and Date Picker Improvements
  demos/app/date-picker/sample.component.html
  demos/app/dialog/sample.component.html
  src/core/styles/components/calendar/_calendar-theme.scss
  src/core/styles/components/date-picker/_date-picker-component.scss
  src/core/styles/components/date-picker/_date-picker-theme.scss
  src/core/styles/components/dialog/_dialog-component.scss
  src/core/styles/components/dialog/_dialog-theme.scss
  src/date-picker/date-picker.component.html
  src/dialog/dialog-content.component.html
  src/dialog/dialog.component.spec.ts
Labels: calendar, date-picker, modal-dialog, status: verified

#773 Grid summary
  demos/app/app.component.ts
  demos/app/app.module.ts
  demos/app/app.routing.ts
  demos/app/grid-summaries/sample.component.css
  demos/app/grid-summaries/sample.component.html
  demos/app/grid-summaries/sample.component.ts
  demos/app/grid-summaries/sample.module.ts
  demos/package-lock.json
  package-lock.json
  src/grid/api.service.ts
  src/grid/column.component.ts
  src/grid/grid-summary.component.html
  src/grid/grid-summary.component.ts
  src/grid/grid-summary.ts
  src/grid/grid.component.html
  src/grid/grid.component.ts
  src/grid/index.ts
Labels: status: in-development

#788 Added a sample for the mask directive in demos
  demos/app/app.component.ts
  demos/app/app.module.ts
  demos/app/app.routing.ts
  demos/app/directives/mask/sample.component.css
  demos/app/directives/mask/sample.component.html
  demos/app/directives/mask/sample.component.ts
  demos/app/directives/mask/sample.module.ts
Labels: demos, mask-editor, status: verified

#784 Checkbox indeterminate state, ripple, and label position
  CHANGELOG.md
  demos/app/input/sample.component.html
  demos/app/input/sample.component.ts
  src/checkbox/checkbox.component.html
  src/checkbox/checkbox.component.spec.ts
  src/checkbox/checkbox.component.ts
  src/core/styles/base/utilities/_bem.scss
  src/core/styles/base/utilities/_functions.scss
  src/core/styles/components/checkbox/_checkbox-component.scss
  src/core/styles/components/checkbox/_checkbox-theme.scss
  src/directives/ripple/ripple.directive.ts
Labels: feature, refactoring, status: verified, version: 5.3.x

#781 #668 Excel export tests
  demos/app/grid/sample.component.html
  demos/app/grid/sample.component.ts
  src/services/excel/excel-exporter-grid.spec.ts
  src/services/excel/excel-exporter.spec.ts
  src/services/excel/excel-exporter.ts
  src/services/excel/excel-strings.ts
  src/services/excel/jsZip-helper.ts
  src/services/excel/jszip-verification-wrapper.ts
  src/services/excel/test-data.service.ts
Labels: status: in-test

#785 feat(bem): add mixin to allow extending multiple modifiers
  src/core/styles/base/utilities/_bem.scss
  src/core/styles/base/utilities/_functions.scss
Labels: feature, status: verified, styling, theme, version: 5.2.x

#779 Fixing change detectin bug related to api paging action
  src/grid/grid.component.ts
  src/grid/grid.pagination.spec.ts
Labels: grid, status: verified

#774 add commitizen validation
  .czrc
  package.json
Labels: status: in-development

#801 Update CHANGELOG.md - add mask directive in 5.3.0
  CHANGELOG.md
Labels: documentation, mask-editor, status: verified, version: 5.3.x

#802 Mask directive improvements
  src/directives/mask/mask-helper.ts
  src/directives/mask/mask.directive.spec.ts
Labels: enhancement, mask-editor, status: verified, version: 5.3.x

#747 IgxGrid Column Pinning (API)
  CHANGELOG.md
  demos/app/app.component.ts
  demos/app/app.module.ts
  demos/app/app.routing.ts
  demos/app/grid-column-pinning/sample.component.css
  demos/app/grid-column-pinning/sample.component.html
  demos/app/grid-column-pinning/sample.component.ts
  demos/app/grid-column-pinning/sample.module.ts
  src/core/styles/components/_common/_igx-vhelper.scss
  src/core/styles/components/grid/_grid-component.scss
  src/core/styles/components/grid/_grid-theme.scss
  src/directives/for-of/for_of.directive.ts
  src/grid/README.md
  src/grid/api.service.ts
  src/grid/cell.component.ts
  src/grid/column.component.ts
  src/grid/grid-header.component.ts
  src/grid/grid.component.html
  src/grid/grid.component.ts
  src/grid/grid.pinning.spec.ts
  src/grid/row.component.html
  src/grid/row.component.ts
Labels: feature, pinning, status: verified, version: 5.3.x

#815 Updating grid readme doc with Column Pinning API
  src/grid/README.md
Labels: documentation, pinning

#818 Update npm deploy tag
  .travis.yml
Labels: build, npm

#819 Change visual design
  src/core/styles/components/grid-summary/_grid-summary-component.scss
  src/core/styles/components/grid-summary/_grid-summary-theme.scss
Labels: status: awaiting-test, styling

#760 Add timepicker control
  CHANGELOG.md
  demos/app/app.component.ts
  demos/app/app.module.ts
  demos/app/app.routing.ts
  demos/app/time-picker/sample.component.css
  demos/app/time-picker/sample.component.html
  demos/app/time-picker/sample.component.ts
  demos/app/time-picker/sample.module.ts
  src/core/styles/components/time-picker/_time-picker-component.scss
  src/core/styles/components/time-picker/_time-picker-theme.scss
  src/core/styles/themes/_core.scss
  src/core/styles/themes/_index.scss
  src/main.ts
  src/time-picker/README.md
  src/time-picker/time-picker.component.html
  src/time-picker/time-picker.component.spec.ts
  src/time-picker/time-picker.component.ts
  src/time-picker/time-picker.directives.ts
Labels: feature, status: verified, time-picker, version: 5.3.x

#822 Fix for issue #816 - When grid width is in % horizontal scrollbar wit…
  src/core/styles/components/grid/_grid-theme.scss
  src/grid/grid.component.html
Labels: grid, pinning, status: verified, version: 5.3.x

#809 IgxGrid summaries
  .travis.yml
  CHANGELOG.md
  demos/app/app.component.ts
  demos/app/app.module.ts
  demos/app/app.routing.ts
  demos/app/directives/mask/sample.component.css
  demos/app/directives/mask/sample.component.html
  demos/app/directives/mask/sample.component.ts
  demos/app/directives/mask/sample.module.ts
  demos/app/grid-column-pinning/sample.component.css
  demos/app/grid-column-pinning/sample.component.html
  demos/app/grid-column-pinning/sample.component.ts
  demos/app/grid-column-pinning/sample.module.ts
  demos/app/grid-summaries/sample.component.html
  demos/app/grid-summaries/sample.component.ts
  demos/app/grid/sample.component.html
  demos/app/grid/sample.component.ts
  demos/app/input/sample.component.html
  demos/app/input/sample.component.ts
  package.json
  src/calendar/calendar.component.html
  src/checkbox/checkbox.component.html
  src/checkbox/checkbox.component.spec.ts
  src/checkbox/checkbox.component.ts
  src/core/styles/base/utilities/_bem.scss
  src/core/styles/base/utilities/_functions.scss
  src/core/styles/components/_common/_igx-vhelper.scss
  src/core/styles/components/calendar/_calendar-theme.scss
  src/core/styles/components/checkbox/_checkbox-component.scss
  src/core/styles/components/checkbox/_checkbox-theme.scss
  src/core/styles/components/grid-summary/_grid-summary-component.scss
  src/core/styles/components/grid-summary/_grid-summary-theme.scss
  src/core/styles/components/grid/_grid-component.scss
  src/core/styles/components/grid/_grid-theme.scss
  src/directives/for-of/for_of.directive.ts
  src/directives/mask/mask-helper.ts
  src/directives/mask/mask.directive.spec.ts
  src/directives/ripple/ripple.directive.ts
  src/grid/README.md
  src/grid/api.service.ts
  src/grid/cell.component.ts
  src/grid/column.component.ts
  src/grid/grid-header.component.ts
  src/grid/grid-summary.component.html
  src/grid/grid-summary.component.ts
  src/grid/grid-summary.spec.ts
  src/grid/grid-summary.ts
  src/grid/grid.component.html
  src/grid/grid.component.ts
  src/grid/grid.pagination.spec.ts
  src/grid/grid.pinning.spec.ts
  src/grid/row.component.html
  src/grid/row.component.ts
  tslint.json
Labels: feature, grid, status: in-progress, version: 5.3.x

#821 Fix and test for issue #808
  src/directives/for-of/for_of.directive.spec.ts
  src/directives/for-of/for_of.directive.ts
Labels: status: verified, version: 5.2.x

#820 Fix and test for issue #808
  src/directives/for-of/for_of.directive.spec.ts
  src/directives/for-of/for_of.directive.ts
Labels: status: verified, version: 5.3.x

#833 Updating RoadMap
  ROADMAP.md
Labels: documentation

#813 Fix and test for issue #807: Cannot read property 'length' of undefin…
  src/directives/for-of/for_of.directive.spec.ts
  src/directives/for-of/for_of.directive.ts
Labels: grid, status: verified, version: 5.3.x, virtualization

#830 Fix and test for issue #826
  src/directives/for-of/for_of.directive.spec.ts
  src/directives/for-of/for_of.directive.ts
Labels: status: verified, version: 5.3.x, virtualization

#831 Fix and test for issue #826
  src/directives/for-of/for_of.directive.spec.ts
  src/directives/for-of/for_of.directive.ts
Labels: status: verified, version: 5.2.x, virtualization

#842 Fix grid rows
  src/core/styles/components/grid-paginator/grid-paginator-component.scss
  src/core/styles/components/grid-paginator/grid-paginator-theme.scss
  src/core/styles/components/grid/_grid-theme.scss
  src/core/styles/themes/_core.scss
  src/core/styles/themes/_index.scss
  src/grid/grid.component.html
Labels: grid, status: awaiting-test, styling

#829 consistent commit messages
  .github/CONTRIBUTING.md
  .hooks/prepare-commit-msg
  .hooks/scripts/common.js
  .hooks/scripts/templateValidators/default-style-validator.js
  .hooks/scripts/templates/default.js
  .hooks/scripts/utils/issue-validator.js
  .hooks/scripts/utils/line-limits.js
  .hooks/scripts/validate.js
  gulpfile.js
  package.json
Labels: status: verified

#840 Fix for issue #838 - When setting the igxForContainerSize post init and binding a new array scrolling with the mouse wheel scrolls the page as well.
  src/directives/for-of/for_of.directive.ts
Labels: status: verified, version: 5.2.x, virtualization

#846 docs: Update docs for checkbox and ripple
  src/checkbox/README.md
  src/directives/ripple/README.md
Labels: documentation, status: verified

#845 Added summaries to IgxGrid
  CHANGELOG.md
  demos/app/app.component.ts
  demos/app/app.module.ts
  demos/app/app.routing.ts
  demos/app/grid-summaries/sample.component.css
  demos/app/grid-summaries/sample.component.html
  demos/app/grid-summaries/sample.component.ts
  demos/app/grid-summaries/sample.module.ts
  demos/package-lock.json
  package-lock.json
  src/core/styles/components/grid-paginator/grid-paginator-component.scss
  src/core/styles/components/grid-paginator/grid-paginator-theme.scss
  src/core/styles/components/grid-summary/_grid-summary-component.scss
  src/core/styles/components/grid-summary/_grid-summary-theme.scss
  src/core/styles/components/grid/_grid-theme.scss
  src/core/styles/themes/_core.scss
  src/core/styles/themes/_index.scss
  src/grid/README.md
  src/grid/api.service.ts
  src/grid/cell.component.ts
  src/grid/column.component.ts
  src/grid/grid-summary.component.html
  src/grid/grid-summary.component.ts
  src/grid/grid-summary.spec.ts
  src/grid/grid-summary.ts
  src/grid/grid.component.html
  src/grid/grid.component.ts
  src/grid/index.ts
Labels: feature, status: verified, summaries

#839 Fix for issue #838 - When setting the igxForContainerSize post init and binding a new array scrolling with the mouse wheel scrolls the page as well
  src/directives/for-of/for_of.directive.ts
Labels: status: verified, version: 5.3.x, virtualization

#861 feat(checkbox): better accessibility, improved event handling
  CHANGELOG.md
  src/checkbox/README.md
  src/checkbox/checkbox.component.html
  src/checkbox/checkbox.component.spec.ts
  src/checkbox/checkbox.component.ts
Labels: checkbox, feature, status: verified, version: 5.3.x

#868 copy the prepare-commit-msg hook correctly
  gulpfile.js
Labels: version: 5.3.x

#852 Change implementation of formatOptions/formatViews inputs
  src/calendar/calendar.component.spec.ts
  src/calendar/calendar.component.ts
  src/date-picker/date-picker.component.ts
Labels: severity: medium, status: verified, version: 5.3.x

#863 Rewrite formatViews description to correctly represent its use
  src/calendar/calendar.component.ts
Labels: calendar, documentation, enhancement, version: 5.3.x
